arguments:
  c_conds:
    - 128
    - 128
    - 128
  n_blocks:
    - 4
    - 8
    - 12
  extractor_name: wide_resnet50_2
  pool_type: avg
  top_k: 0.03
  img_size:
    - 512
    - 512
class_name: MSFlowModel